# Generated by Django 4.0.3 on 2022-04-15 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Month',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In-progress'), ('complete', 'Complete')], default='pending', max_length=50)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.month')),
            ],
            options={
                'verbose_name': 'Task',
            },
        ),
    ]
